# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.28.7"

default_platform :android

platform :android do

  before_all do
    ENV["ARTIFACTS"] = "./app/build/outputs"
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :betaMaster do |options|
    commit = last_git_commit
    crashlytics(
          apk_path: ENV["ARTIFACTS"] + '/apk/app-debug.apk',
          groups: "DroiDon",
          api_token: ENV["FABRIC_API_KEY"],
          build_secret: ENV["FABRIC_API_SECRET"],
          notes: git_branch << ':' << commit[:commit_hash][0, 7] << ' ' << commit[:message],
          crashlytics_path: './fastlane/crashlytics-devtools.jar'
    )
  end
end

# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md

# fastlane reports which actions are used
# No personal data is sent or shared. Learn more at https://github.com/fastlane/enhancer
